#define SuperCHMethod0(return_type, class_type, name) CHSuper0(class_type, name)
#define SuperCHMethod1(return_type, class_type, name1, type1, arg1) CHSuper1(class_type, name1, arg1)
#define SuperCHMethod2(return_type, class_type, name1, type1, arg1, name2, type2, arg2) CHSuper2(class_type, name1, arg1, name2, arg2)
#define SuperCHMethod3(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3) CHSuper3(class_type, name1, arg1, name2, arg2, name3, arg3)
#define SuperCHMethod4(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4) CHSuper4(class_type, name1, arg1, name2, arg2, name3, arg3, name4, arg4)
#define SuperCHMethod5(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5) CHSuper5(class_type, name1, arg1, name2, arg2, name3, arg3, name4, arg4, name5, arg5)
#define SuperCHMethod6(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5, name6, type6, arg6) CHSuper6(class_type, name1, arg1, name2, arg2, name3, arg3, name4, arg4, name5, arg5, name6, arg6)

#define HookCHMethod0(return_type, class_type, name) CHHook0(class_type, name)
#define HookCHMethod1(return_type, class_type, name1, type1, arg1) CHHook1(class_type, name1)
#define HookCHMethod2(return_type, class_type, name1, type1, arg1, name2, type2, arg2) CHHook2(class_type, name1, name2)
#define HookCHMethod3(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3) CHHook3(class_type, name1, name2, name3)
#define HookCHMethod4(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4) CHHook4(class_type, name1, name2, name3, name4)
#define HookCHMethod5(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5) CHHook5(class_type, name1, name2, name3, name4, name5)
#define HookCHMethod6(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5, name6, type6, arg6) CHHook6(class_type, name1, name2, name3, name4, name5, name6)

#define ClassHookCHMethod0(return_type, class_type, name) CHClassHook0(class_type, name)
#define ClassHookCHMethod1(return_type, class_type, name1, type1, arg1) CHClassHook1(class_type, name1)
#define ClassHookCHMethod2(return_type, class_type, name1, type1, arg1, name2, type2, arg2) CHClassHook2(class_type, name1, name2)
#define ClassHookCHMethod3(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3) CHClassHook3(class_type, name1, name2, name3)
#define ClassHookCHMethod4(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4) CHClassHook4(class_type, name1, name2, name3, name4)
#define ClassHookCHMethod5(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5) CHClassHook5(class_type, name1, name2, name3, name4, name5)
#define ClassHookCHMethod6(return_type, class_type, name1, type1, arg1, name2, type2, arg2, name3, type3, arg3, name4, type4, arg4, name5, type5, arg5, name6, type6, arg6) CHClassHook6(class_type, name1, name2, name3, name4, name5, name6)

